openapi: 3.0.0
info:
  title: Orders API
  version: 1.0.0
  description: API for order management in the clothes e-commerce app

paths:
  /api/orders:
    post:
      summary: Create new order
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrderRequest'
      responses:
        '200':
          description: Order created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  order:
                    $ref: '#/components/schemas/Order'
        '400':
          description: Invalid input or insufficient stock
        '401':
          description: Unauthorized

  /api/orders/user/{userId}:
    get:
      summary: Get user's orders
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
        - name: limit
          in: query
          schema:
            type: integer
            default: 10
        - name: offset
          in: query
          schema:
            type: integer
            default: 0
      responses:
        '200':
          description: List of user's orders
          content:
            application/json:
              schema:
                type: object
                properties:
                  orders:
                    type: array
                    items:
                      $ref: '#/components/schemas/OrderSummary'
                  total:
                    type: integer

  /api/orders/{orderId}:
    get:
      summary: Get specific order
      parameters:
        - name: orderId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Order details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        '404':
          description: Order not found
        '401':
          description: Unauthorized

components:
  schemas:
    OrderRequest:
      type: object
      properties:
        items:
          type: array
          items:
            type: object
            properties:
              productId:
                type: string
              quantity:
                type: integer
                minimum: 1
              size:
                type: string
              color:
                type: string
            required:
              - productId
              - quantity
              - size
        shippingAddress:
          $ref: '#/components/schemas/Address'
        billingAddress:
          $ref: '#/components/schemas/Address'
        paymentMethod:
          type: string
          enum: [COD]
        notes:
          type: string
      required:
        - items
        - shippingAddress
        - paymentMethod

    Order:
      type: object
      properties:
        id:
          type: string
        userId:
          type: string
        items:
          type: array
          items:
            $ref: '#/components/schemas/OrderItem'
        totalAmount:
          type: integer
        shippingAddress:
          $ref: '#/components/schemas/Address'
        billingAddress:
          $ref: '#/components/schemas/Address'
        paymentMethod:
          type: string
          enum: [COD]
        status:
          type: string
          enum: [pending, confirmed, processing, shipped, delivered, cancelled]
        orderDate:
          type: string
          format: date-time
        estimatedDelivery:
          type: string
          format: date-time
        notes:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
      required:
        - id
        - userId
        - items
        - totalAmount
        - shippingAddress
        - paymentMethod
        - status
        - orderDate
        - createdAt
        - updatedAt

    OrderSummary:
      type: object
      properties:
        id:
          type: string
        totalAmount:
          type: integer
        status:
          type: string
        orderDate:
          type: string
          format: date-time
        itemCount:
          type: integer

    OrderItem:
      type: object
      properties:
        productId:
          type: string
        productName:
          type: string
        quantity:
          type: integer
        price:
          type: integer
        size:
          type: string
        color:
          type: string
      required:
        - productId
        - productName
        - quantity
        - price
        - size

    Address:
      type: object
      properties:
        street:
          type: string
        city:
          type: string
        state:
          type: string
        zipCode:
          type: string
        country:
          type: string
      required:
        - street
        - city
        - state
        - zipCode
        - country